name: Trigger Dependent Projects

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger autoPublisher project
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            https://api.github.com/repos/OMGerEDU/Youtube-Publisher/dispatches \
            -d '{"event_type": "update-versioning-scripts"}'
