name: Trigger Update

on:
  push:
    branches:
      - main

jobs:
  trigger_update:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger repository_dispatch event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: YourGitHubUsername/AutoChannelPublisher
        event-type: update-versioning-scripts
